{smcl}
{* *! version 1.0.0  06oct2026}{...}
{vieweralsosee "jointdiag" "help jointdiag"}{...}
{vieweralsosee "jointdiag methods" "help jointdiag_methods"}{...}
{vieweralsosee "jointdiag arch" "help jointdiag_arch"}{...}
{vieweralsosee "jointdiag score" "help jointdiag_score"}{...}
{viewerjumpto "Syntax" "jointdiag_bilinear##syntax"}{...}
{viewerjumpto "Description" "jointdiag_bilinear##description"}{...}
{viewerjumpto "Options" "jointdiag_bilinear##options"}{...}
{viewerjumpto "Interpreting the output" "jointdiag_bilinear##interpret"}{...}
{viewerjumpto "Remarks" "jointdiag_bilinear##remarks"}{...}
{viewerjumpto "Examples" "jointdiag_bilinear##examples"}{...}
{viewerjumpto "Stored results" "jointdiag_bilinear##results"}{...}

{title:Title}

{phang}
{bf:jointdiag bilinear} {hline 2} ARCH versus bilinearity: a joint test for
nonlinear dependence


{marker syntax}{...}
{title:Syntax}

{p 8 17 2}
{cmd:jointdiag} {cmd:bilinear} [{it:depvar} {it:indepvars}] {ifin}
[{cmd:,} {it:options}]

{synoptset 24 tabbed}{...}
{synopthdr}
{synoptline}
{synopt:{opt archl:ags(#)}}ARCH order {it:q}; default {cmd:archlags(1)}{p_end}
{synopt:{opt r(#)}}first bilinear order; default {cmd:r(1)}{p_end}
{synopt:{opt s(#)}}second bilinear order, must satisfy {it:s} {&le} {it:r};
default {cmd:s(1)}{p_end}
{synopt:{opt f:form}}use the locally equivalent alternative F form with the
factor-2 correction{p_end}
{synopt:{opt l:evel(#)}}confidence level{p_end}
{synopt:{opt gr:aph}}component plot{p_end}
{synopt:{opt name(string)}}graph name{p_end}
{synopt:{opt notab:le}}suppress the table{p_end}
{synoptline}


{marker description}{...}
{title:Description}

{pstd}
ARCH and bilinear processes are easily confused, and the confusion matters
because they have opposite practical implications.

{p 4 7 2}
Under {bf:ARCH} the conditional mean is unchanged: past observations tell you
about future {it:variances} only, so detecting ARCH cannot improve a point
forecast.

{p 4 7 2}
Under {bf:bilinearity} the conditional mean is augmented with interaction terms
between past errors and innovations, so detecting it {it:can} improve a point
forecast.

{pstd}
Yet their unconditional moment structures are nearly identical.  Both are
serially uncorrelated in levels; both are autocorrelated in squares, with the
squares following an ARMA process in each case; both display volatility
clustering.  Since the standard diagnostics {c 150} the autocorrelations of the
squared residuals, Engle's LM test, the McLeod{c 150}Li portmanteau {c 150} are
all built from those unconditional moments, they cannot tell the two apart.

{pstd}
This command computes the joint LM test, which answers "is there nonlinear
dependence" without pretending to answer "of which kind".


{marker options}{...}
{title:Options}

{phang}
{opt archlags(#)}, {opt r(#)} and {opt s(#)} set the three orders.  The
constraint {it:s} {&le} {it:r} is not cosmetic: no LM test exists against an
alternative containing both {it:u_{t-i}e_{t-j}} and {it:u_{t-j}e_{t-i}}, so
{it:b_ij} is set to zero for {it:i} < {it:j} (Saikkonen and Luukkonen 1988).
For the same reason the variance side is ARCH rather than GARCH: no LM test
exists against lagged conditional variances (Bollerslev 1986).

{phang}
{opt fform} switches from two separate {it:nR}{c 178} statistics to the single
artificial regression of Bera and Higgins (1997, eq. 3.4), from which two
F statistics are read off.  {bf:The ARCH F is then halved}: the ordinary
regression variance of that block is exactly half the correct asymptotic
variance, so an uncorrected F over-rejects by a factor of two.  This is the
same factor-2 correction that appears in {helpb jointdiag_lm:jointdiag lm}'s
{cmd:studentize} and in {helpb jointdiag_nonnest:jointdiag nonnest}.


{marker interpret}{...}
{title:Interpreting the output}

{pstd}
{bf:Both rejecting is the normal case, not a contradiction.}  Because the two
processes share their unconditional moments, data generated by either will
usually reject both.  The joint statistic is the honest summary: there is
nonlinear dependence.

{pstd}
{bf:What to do next.}  The joint test does not choose between the models.  Bera
and Higgins (1997, sec. 4) choose with a stochastically simulated Cox test;
applied to three weekly dollar exchange rates they found GARCH adequate for the
British pound, bilinearity preferred for the Canadian dollar, and {it:both}
rejected for the Japanese yen.  That procedure is not implemented here {c 150}
it needs a full likelihood simulation per replication {c 150} so the practical
route is: fit both, compare information criteria, and check which one leaves
clean standardised residuals under {helpb jointdiag_port:jointdiag port}.

{pstd}
{bf:If only the bilinear block rejects} you have evidence of forecastable
nonlinearity in the conditional mean, which is worth more than a variance
model.


{marker remarks}{...}
{title:Remarks}

{pstd}
{bf:Why additivity holds.}  The two blocks of regressors in the locally
equivalent alternative {c 150} the lagged squared residuals for ARCH, the
cross-products of lagged residuals for bilinearity {c 150} are asymptotically
orthogonal, so the Bera{c 150}McKenzie condition is satisfied and the LM
statistics add.  Higgins and Bera (1988, sec. 2) state the condition; see
{helpb jointdiag_methods##additivity:jointdiag methods}.

{pstd}
{bf:A caution about the literature.}  Several of the source papers cite this
result as "Higgins and Bera (1989)".  The published article is
{it:Econometric Reviews} {bf:7}(2), 171{c 150}181, {bf:1988}.


{marker examples}{...}
{title:Examples}

{phang2}{cmd:. webuse lutkepohl2, clear}{p_end}
{phang2}{cmd:. regress dln_inv dln_inc}{p_end}

{pstd}First order in both directions{p_end}
{phang2}{cmd:. jointdiag bilinear, archlags(1) r(1) s(1)}{p_end}

{pstd}Richer alternative, F form with the variance correction{p_end}
{phang2}{cmd:. jointdiag bilinear, archlags(2) r(2) s(1) fform graph}{p_end}


{marker results}{...}
{title:Stored results}

{synoptset 26 tabbed}{...}
{p2col 5 26 30 2: Scalars}{p_end}
{synopt:{cmd:r(lm_arch)}, {cmd:r(df_arch)}, {cmd:r(p_arch)}}ARCH block{p_end}
{synopt:{cmd:r(lm_bilinear)}, {cmd:r(df_bilinear)}, {cmd:r(p_bilinear)}}bilinear
block{p_end}
{synopt:{cmd:r(lm_joint)}, {cmd:r(df_joint)}, {cmd:r(p_joint)}}their sum{p_end}
{synopt:{cmd:r(N)}}observations{p_end}


{title:References}

{phang}Higgins, M. L., and A. K. Bera. 1988. {it:Econometric Reviews} 7: 171{c 150}181.
{browse "https://doi.org/10.1080/07474938808800151"}{p_end}
{phang}Bera, A. K., and M. L. Higgins. 1997. {it:JBES} 15: 43{c 150}50.
{browse "https://doi.org/10.1080/07350015.1997.10524685"}{p_end}
{phang}Granger, C. W. J., and A. P. Andersen. 1978.
{it:An Introduction to Bilinear Time Series Models}.
Gottingen: Vandenhoeck and Ruprecht.{p_end}


{title:Author}

{pstd}
Dr Merwan Roudane{break}
{browse "mailto:merwanroudane920@gmail.com":merwanroudane920@gmail.com}{break}
{browse "https://github.com/merwanroudane":github.com/merwanroudane}
