{smcl}
{* *! version 2.0.0 25sep2026}
{title:cvcombo v2.0}

{pstd}
{bf:Control-variable all-combinations robustness test}

{p 4 8}{bf:Authors:} Jiang ZhenYuan (蒋镇源) and Zhang Na (张娜){p_end}
{p 4 8}{bf:Affiliation:} School of Economics, Northwest Normal University{p_end}
{p 4 8}{bf:Support:} kangjang504@gmail.com; zhangna@nwnu.edu.cn{p_end}
{p 4 8}{bf:Version:} 2.0.0{p_end}
{p 4 8}{bf:Date:} 26 September 2026{p_end}
{p 4 8}{bf:Requires:} Stata 15.1 or later{p_end}

{title:Syntax}
{p 8 12}{cmd:cvcombo} {it:depvar mainvar}, {cmd:method(}{it:command}{cmd:)} {cmd:controls(}{it:control_list}{cmd:)}{p_end}
{p 8 12}{cmd:}[{cmd:options(}{it:method_options}{cmd:)} {cmd:absorb(}{it:fe_vars}{cmd:)} {cmd:cluster(}{it:cluster_var}{cmd:)} {cmd:samplevars(}{it:varlist}{cmd:)} {cmd:level(}{it:#}{cmd:)} {cmd:saving(}{it:filename}{cmd:)} {cmd:replace} {cmd:graphprefix(}{it:prefix}{cmd:)} {cmd:paper} {cmd:paperdir(}{it:folder}{cmd:)} {cmd:docx(}{it:filename}{cmd:)} {cmd:nograph}]

{title:Description}
{pstd}
{cmd:cvcombo} estimates every nonempty subset of the candidate control variables. With {it:k} candidate controls, the command estimates {cmd:2^k - 1} specifications. The coefficient on the main explanatory variable is recorded for every successful specification, together with its standard error, test statistic, p-value, confidence interval, coefficient direction, number of controls, and estimation sample size.{p_end}

{pstd}
The estimation command is supplied by the user through {cmd:method()}. This makes {cmd:cvcombo} generic rather than hard-coded to a particular estimator. The estimator should accept an {cmd:if} qualifier and return {cmd:_b[mainvar]} and {cmd:_se[mainvar]}. Examples include {cmd:regress}, {cmd:xtreg}, {cmd:logit}, {cmd:probit}, and {cmd:reghdfe}.{p_end}

{title:Options}
{phang}{cmd:method(}{it:command}{cmd:)} specifies the estimator that will be executed for every control-variable combination. {p_end}
{phang}{cmd:controls(}{it:control_list}{cmd:)} specifies the candidate controls. All nonempty combinations are estimated.{p_end}
{phang}{cmd:options(}{it:method_options}{cmd:)} passes method-specific options through to the estimator.{p_end}
{phang}{cmd:absorb(}{it:fe_vars}{cmd:)} is a convenience option for estimators such as {cmd:reghdfe}; it appends {cmd:absorb()} to the estimator call.{p_end}
{phang}{cmd:cluster(}{it:cluster_var}{cmd:)} is a convenience option for clustered inference; it appends {cmd:vce(cluster ...)} to the estimator call.{p_end}
{phang}{cmd:samplevars(}{it:varlist}{cmd:)} adds variables used only in estimator options to the common estimation sample.{p_end}
{phang}{cmd:level(}{it:#}{cmd:)} specifies the confidence level; default is 95.{p_end}
{phang}{cmd:saving(}{it:filename}{cmd:)} saves the machine-readable specification results in a Stata dataset.{p_end}
{phang}{cmd:replace} permits replacement of an existing results file.{p_end}
{phang}{cmd:graphprefix(}{it:prefix}{cmd:)} specifies the prefix for graph files.{p_end}
{phang}{cmd:paper} additionally creates the paper-output bundle: Specification Curve, coefficient distribution, coefficient-by-number-of-controls boxplot, Specification Matrix, ranked coefficient and confidence-interval plot, CSV summary, and a Word Table 8.{p_end}
{phang}{cmd:paperdir(}{it:folder}{cmd:)} specifies the folder used by {cmd:paper}. Existing folders are accepted.{p_end}
{phang}{cmd:docx(}{it:filename}{cmd:)} specifies the Word filename generated by the {cmd:paper} option.{p_end}
{phang}{cmd:nograph} suppresses graph output when the {cmd:paper} option is not requested.{p_end}

{title:Inference}
{pstd}
When the estimator returns {cmd:e(df_r)}, {cmd:cvcombo} uses a t distribution for two-sided inference and confidence intervals. When {cmd:e(df_r)} is unavailable, standard-normal inference is used.{p_end}

{title:Results}
{pstd}
The all-controls baseline model is stored as {cmd:CVCOMBO_BASELINE}.{p_end}

{pstd}
The specification results dataset contains the following key variables:{p_end}
{phang}{cmd:model} specification identifier{p_end}
{phang}{cmd:nctrl} number of included controls{p_end}
{phang}{cmd:ok} estimation success indicator{p_end}
{phang}{cmd:b} coefficient on the main explanatory variable{p_end}
{phang}{cmd:se} standard error{p_end}
{phang}{cmd:t} test statistic{p_end}
{phang}{cmd:p} two-sided p-value{p_end}
{phang}{cmd:lo hi} confidence-interval endpoints{p_end}
{phang}{cmd:direction} coefficient direction: -1, 0, 1{p_end}
{phang}{cmd:controls_str} included control variables{p_end}

{title:Examples}
{phang2}{cmd:. sysuse auto, clear}{p_end}
{phang2}{cmd:. cvcombo mpg weight, method(regress) controls(length headroom trunk) saving(cvcombo_auto.dta) replace}{p_end}

{phang2}{cmd:. cvcombo foreign weight, method(logit) controls(mpg length headroom trunk) saving(cvcombo_logit.dta) replace}{p_end}

{phang2}{cmd:. cvcombo LS Demand, method(reghdfe) controls(Size Lev Employee Growth Age CAP WW HHI) absorb(id year) cluster(id) samplevars(id year) saving(cvcombo_results.dta) replace}{p_end}

{phang2}{cmd:. cvcombo LS Demand, method(reghdfe) controls(Size Lev Employee Growth Age CAP WW HHI) absorb(id year) cluster(id) samplevars(id year) saving(cvcombo_results.dta) replace paper paperdir(cvcombo_paper_output)}{p_end}

{title:Paper output}
{pstd}
With {cmd:paper}, graphs are exported in SVG, PNG, and GPH formats. SVG export uses an explicit Arial font, and figure labels are intentionally written in English/ASCII so that the files do not depend on local Chinese-font rendering. The Word table uses Unicode Chinese text and Microsoft YaHei where available.{p_end}

{title:Dependencies}
{pstd}
{cmd:cvcombo} does not require {cmd:reghdfe} unless {cmd:method(reghdfe)} is used. Users choosing {cmd:method(reghdfe)} should install {cmd:reghdfe} separately from SSC.{p_end}

{title:License}
{pstd}Released under the MIT License.{p_end}
